// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TemplateExample.Models;

public partial class Products
{
    /// <summary>
    /// Primary key
    /// </summary>
    public int ProductID { get; set; }

    /// <summary>
    /// Name
    /// </summary>
    public string ProductName { get; set; }

    /// <summary>
    /// Category key
    /// </summary>
    public int? CategoryID { get; set; }

    /// <summary>
    /// Price
    /// </summary>
    public decimal? UnitPrice { get; set; }

    /// <summary>
    /// How many are in stock
    /// </summary>
    public short? UnitsInStock { get; set; }

    public virtual Categories Category { get; set; }
}