// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TemplateExample.Models;

namespace TemplateExample.Data.Configurations;

public partial class ProductsConfiguration : IEntityTypeConfiguration<Products>
{
    public void Configure(EntityTypeBuilder<Products> entity)
    {
        entity.HasKey(e => e.ProductID);

        entity.HasIndex(e => e.CategoryID, "IX_Products_CategoryID");

        entity.Property(e => e.ProductID).HasComment("Primary key");
        entity.Property(e => e.CategoryID).HasComment("Category key");
        entity.Property(e => e.ProductName)
            .IsRequired()
            .HasMaxLength(40)
            .HasComment("Name");
        entity.Property(e => e.UnitPrice)
            .HasComment("Price")
            .HasColumnType("money");
        entity.Property(e => e.UnitsInStock).HasComment("How many are in stock");

        entity.HasOne(d => d.Category).WithMany(p => p.Products)
            .HasForeignKey(d => d.CategoryID)
            .HasConstraintName("FK_Products_Categories");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<Products> entity);
}